name: my_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_markdown: ^0.6.15
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  path: ^1.9.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.3.0
  flutter_feather_icons: ^2.0.0+1
  shimmer: ^3.0.0
  share_plus: ^7.0.1
  badges: ^2.0.3
  confetti: ^0.7.0
  lottie: ^2.7.0
  url_launcher: ^6.1.11
  clipboard: ^0.1.3
  image: ^4.0.17
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"

# ИСПРАВЛЕННЫЙ ПУТЬ К ИКОНКЕ
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"  # ← ИСПРАВЛЕНО
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon.png"  # ← ИСПРАВЛЕНО

flutter:
  uses-material-design: true

  assets:
    - assets/images/register.png
    - assets/images/icon.png
    - assets/images/articles_images/article_cover/
    - assets/images/articles_images/photo_for_articles/
    - assets/images/event_photos/
    - assets/images/predictions_league_image/
    - assets/images/cards_image/avatarka/
    - assets/images/cards_image/owner/