import 'package:flutter/material.dart';
import 'event_model.dart';

class EventData {
  static List<Event> get featuredEvents => [
    Event(
      id: '1',
      title: 'Концерт Рок-Групп',
      description: 'Приходите все будет весело',
      date: DateTime(2025, 10, 19, 0, 0), // 19 октября 2025 года 00:00
      endDate: DateTime(2025, 10, 20, 0, 0), // 20 октября 2025 года 00:00
      color: Colors.purple,
      category: 'Фестиваль',
      organizer: 'Концертное агентство "Музыка"',
      imageUrl: 'assets/images/event_photos/concert.png',
      tags: ['музыка', 'живое исполнение', 'развлечения', 'вечер'],
      maxAttendees: 1,
      currentAttendees: 0,
      price: 9999,
      rating: 10,
      reviewCount: 5,
      isOnline: false,
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Event(
      id: '2',
      title: 'Выставка современного искусства',
      description: 'Работы молодых художников и скульпторов. Инновации в искусстве и цифровые инсталляции.',
      date: DateTime.now().add(const Duration(days: 5, hours: 11)),
      endDate: DateTime.now().add(const Duration(days: 5, hours: 20)),
      color: Colors.blue,
      category: 'Выставки',
      location: 'Городской музей',
      address: 'пр. Культуры, 45',
      price: 500,
      organizer: 'Музей искусств',
      imageUrl: 'assets/images/event_photos/exhibition_picture.png',
      tags: ['искусство', 'культура', 'выставка', 'современное'],
      maxAttendees: 200,
      currentAttendees: 89,
      rating: 4.6,
      reviewCount: 89,
      isOnline: false,
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 15)),
      updatedAt: DateTime.now().subtract(const Duration(days: 7)),
    ),
    Event(
      id: '3',
      title: 'Фестиваль еды',
      description: 'Гастрономический праздник с шеф-поварами со всего мира. Дегустации, мастер-классы и конкурсы.',
      date: DateTime.now().add(const Duration(days: 7, hours: 12)),
      endDate: DateTime.now().add(const Duration(days: 7, hours: 23)),
      color: Colors.orange,
      category: 'Фестивали',
      location: 'Центральный парк',
      address: 'Центральный парк культуры',
      price: 800,
      organizer: 'Гастрономическая ассоциация',
      imageUrl: 'assets/images/event_photos/food.png',
      tags: ['еда', 'фестиваль', 'гастрономия', 'кулинария'],
      maxAttendees: 1000,
      currentAttendees: 623,
      rating: 4.9,
      reviewCount: 256,
      isOnline: false,
      isFeatured: true,
      createdAt: DateTime.now().subtract(const Duration(days: 20)),
      updatedAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
  ];

  static List<Event> get additionalEvents => [
    Event(
      id: '4',
      title: 'Мастер-класс по программированию',
      description: 'Изучите основы Flutter и Dart с опытными разработчиками. Практические задания и реальные проекты.',
      date: DateTime.now().add(const Duration(days: 4, hours: 14)),
      endDate: DateTime.now().add(const Duration(days: 4, hours: 18)),
      color: Colors.indigo,
      category: 'Образование',
      location: 'IT Академия',
      address: 'ул. Технологическая, 67',
      price: 2000,
      organizer: 'IT Сообщество',
      imageUrl: 'assets/images/event_photos/programming.png',
      tags: ['программирование', 'обучение', 'технологии', 'Flutter'],
      maxAttendees: 50,
      currentAttendees: 35,
      rating: 4.7,
      reviewCount: 42,
      isOnline: true,
      onlineLink: 'https://meet.google.com/abc-def-ghi',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Event(
      id: '5',
      title: 'Бесплатный йога-урок в парке',
      description: 'Утренняя йога для всех желающих на свежем воздухе. Подходит для любого уровня подготовки.',
      date: DateTime.now().add(const Duration(days: 1, hours: 8)),
      endDate: DateTime.now().add(const Duration(days: 1, hours: 9)),
      color: Colors.green,
      category: 'Спорт',
      location: 'Городской парк',
      address: 'Центральный парк',
      price: 0,
      organizer: 'Йога-студия "Гармония"',
      imageUrl: 'assets/images/event_photos/yoga.png',
      tags: ['йога', 'здоровье', 'бесплатно', 'утро', 'спорт'],
      maxAttendees: 100,
      currentAttendees: 78,
      rating: 4.5,
      reviewCount: 67,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Event(
      id: '6',
      title: 'Театральная премьера "Гамлет"',
      description: 'Современная интерпретация классической пьесы Шекспира в постановке известного режиссера.',
      date: DateTime.now().add(const Duration(days: 3, hours: 19)),
      endDate: DateTime.now().add(const Duration(days: 3, hours: 22)),
      color: Colors.red,
      category: 'Театр',
      location: 'Драматический театр',
      address: 'пл. Театральная, 1',
      price: 1200,
      organizer: 'Городской театр',
      imageUrl: 'assets/images/event_photos/theater.png',
      tags: ['театр', 'премьера', 'классика', 'культура'],
      maxAttendees: 300,
      currentAttendees: 245,
      rating: 4.8,
      reviewCount: 156,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 7)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Event(
      id: '7',
      title: 'Бизнес-митап для стартапов',
      description: 'Встреча предпринимателей и инвесторов. Питч-сессии и нетворкинг.',
      date: DateTime.now().add(const Duration(days: 6, hours: 18)),
      endDate: DateTime.now().add(const Duration(days: 6, hours: 21)),
      color: Colors.teal,
      category: 'Встречи',
      location: 'Бизнес-центр "Старт"',
      address: 'ул. Деловая, 15',
      price: 500,
      organizer: 'Сообщество предпринимателей',
      imageUrl: 'assets/images/event_photos/bussines.png',
      tags: ['бизнес', 'митап', 'стартапы', 'нетворкинг'],
      maxAttendees: 150,
      currentAttendees: 112,
      rating: 4.6,
      reviewCount: 78,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 12)),
      updatedAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Event(
      id: '8',
      title: 'Мастер-класс по кулинарии',
      description: 'Учимся готовить итальянскую пасту от шеф-повара. Все ингредиенты включены.',
      date: DateTime.now().add(const Duration(days: 8, hours: 16)),
      endDate: DateTime.now().add(const Duration(days: 8, hours: 19)),
      color: Colors.orange,
      category: 'Образование',
      location: 'Кулинарная студия "Вкусно"',
      address: 'пр. Гастрономический, 23',
      price: 2500,
      organizer: 'Школа кулинарии',
      imageUrl: 'assets/images/event_photos/cook.png',
      tags: ['кулинария', 'мастер-класс', 'итальянская кухня', 'еда'],
      maxAttendees: 20,
      currentAttendees: 18,
      rating: 4.9,
      reviewCount: 34,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    Event(
      id: '9',
      title: 'Беговой марафон "Городские улицы"',
      description: 'Ежегодный городской марафон на 10 км. Участвуют бегуны всех уровней.',
      date: DateTime.now().add(const Duration(days: 10, hours: 9)),
      endDate: DateTime.now().add(const Duration(days: 10, hours: 13)),
      color: Colors.green,
      category: 'Спорт',
      location: 'Центральный стадион',
      address: 'пр. Спортивный, 10',
      price: 800,
      organizer: 'Федерация легкой атлетики',
      imageUrl: 'assets/images/event_photos/running.png',
      tags: ['марафон', 'бег', 'спорт', 'здоровье'],
      maxAttendees: 1000,
      currentAttendees: 756,
      rating: 4.7,
      reviewCount: 203,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 30)),
      updatedAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    Event(
      id: '10',
      title: 'Лекция по искусственному интеллекту',
      description: 'Современные тенденции в AI и машинном обучении. Для разработчиков и энтузиастов.',
      date: DateTime.now().add(const Duration(days: 12, hours: 17)),
      endDate: DateTime.now().add(const Duration(days: 12, hours: 19)),
      color: Colors.indigo,
      category: 'Образование',
      location: 'Технопарк',
      address: 'ул. Инновационная, 8',
      price: 0,
      organizer: 'AI Сообщество',
      imageUrl: 'assets/images/event_photos/ai.png',
      tags: ['AI', 'технологии', 'лекция', 'бесплатно', 'образование'],
      maxAttendees: 200,
      currentAttendees: 167,
      rating: 4.8,
      reviewCount: 89,
      isOnline: true,
      onlineLink: 'https://meet.google.com/xyz-abc-def',
      createdAt: DateTime.now().subtract(const Duration(days: 10)),
      updatedAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    Event(
      id: '11',
      title: 'Фотовыставка "Город в объективе"',
      description: 'Работы лучших городских фотографов. Уличная фотография и архитектура.',
      date: DateTime.now().add(const Duration(days: 15, hours: 11)),
      endDate: DateTime.now().add(const Duration(days: 15, hours: 20)),
      color: Colors.blue,
      category: 'Выставки',
      location: 'Галерея современного искусства',
      address: 'ул. Художественная, 34',
      price: 300,
      organizer: 'Союз фотографов',
      imageUrl: 'assets/images/event_photos/city.png',
      tags: ['фотография', 'выставка', 'искусство', 'город'],
      maxAttendees: 100,
      currentAttendees: 45,
      rating: 4.5,
      reviewCount: 23,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 14)),
      updatedAt: DateTime.now().subtract(const Duration(days: 6)),
    ),
    Event(
      id: '12',
      title: 'Джазовый вечер в клубе',
      description: 'Живые выступления местных джазовых коллективов. Уютная атмосфера.',
      date: DateTime.now().add(const Duration(days: 9, hours: 20)),
      endDate: DateTime.now().add(const Duration(days: 9, hours: 23)),
      color: Colors.purple,
      category: 'Концерты',
      location: 'Джаз-клуб "Блюз"',
      address: 'ул. Музыкальная, 56',
      price: 1000,
      organizer: 'Джазовое сообщество',
      imageUrl: 'assets/images/event_photos/juzz.png',
      tags: ['джаз', 'музыка', 'живое выступление', 'клуб'],
      maxAttendees: 80,
      currentAttendees: 72,
      rating: 4.9,
      reviewCount: 45,
      isOnline: false,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
      updatedAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
  ];

  static List<Event> getAllEvents() {
    return [...featuredEvents, ...additionalEvents];
  }
}